server:
  port: 8484

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring
    username: root
    password: mariadb
  jpa:
    # SQL??? ?? ? ?? DBMS? ???? ??? ????
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      # ddl? ???? ??
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true   # SQL ??? ????? ??? ?? ??
    database: mysql  # DBMS ?? ??

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    com.study.todoapi : debug


jwt:
  secret: /aSAfrn4b1lBYJyJyDUvphlSyZucyY9570ZCpRzP5S+Fstak+086k7cd/LAluhyOx5QTzjtwD4SOjZnl5ciQjRQ==
